[program:dev-vibeui-octane]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/fahril/PROJECTS/Teknovate/vibe-ui/artisan octane:start --server=frankenphp --host=127.0.0.1 --port=8000 --workers=auto --max-requests=500
directory=/home/fahril/PROJECTS/Teknovate/vibe-ui
autostart=true
autorestart=true
user=fahril
redirect_stderr=true
stdout_logfile=/home/fahril/PROJECTS/Teknovate/vibe-ui/storage/logs/octane.log
stopwaitsecs=3600
stopsignal=SIGTERM
